### ISSUE TITLE
Cursor calculation on page scroll

### ISSUE THREAD

**Issue by krzo93** [codrops/ImageGridMotionEffect#1]
Hi, 

First, thank you for this amazing library. I've used it first time now and I noticed that it works fine if the gallery is full-width and full-height. 

I've got an example where the gallery is down the page and realized that the gallery is not broken, but images are moved way too much down because cursor Y position is calculated strangely on page scroll (it's like doubled what should be or even more.) 

Do you maybe know what could be the problem or if you experienced something similar?

Thanks in advance.

**Comment by botelho** [comment]
Hi Matic, thank you for your message.
I've just updated the function "getMousePos" in js/utils.js 
It should be working now. Let me know and thanks again.
